/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xiaying.renascence;

public interface RenascenceBasicConstants {
  public final static int GP_OPTIMIZOR_VALUE = RenascenceBasicJNI.GP_OPTIMIZOR_VALUE_get();
  public final static int GP_OPTIMIZOR_TIME = RenascenceBasicJNI.GP_OPTIMIZOR_TIME_get();

}
