/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/GPDAG.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/GPDAG.pb-c.h"
void   gp__point__init
                     (GP__Point         *message)
{
  static GP__Point init_value = GP__POINT__INIT;
  *message = init_value;
}
size_t gp__point__get_packed_size
                     (const GP__Point *message)
{
  assert(message->base.descriptor == &gp__point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gp__point__pack
                     (const GP__Point *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gp__point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gp__point__pack_to_buffer
                     (const GP__Point *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gp__point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GP__Point *
       gp__point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GP__Point *)
     protobuf_c_message_unpack (&gp__point__descriptor,
                                allocator, len, data);
}
void   gp__point__free_unpacked
                     (GP__Point *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &gp__point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue gp__point__type__enum_values_by_number[5] =
{
  { "FUNCTION", "GP__POINT__TYPE__FUNCTION", 0 },
  { "INPUT", "GP__POINT__TYPE__INPUT", 1 },
  { "STRING", "GP__POINT__TYPE__STRING", 2 },
  { "PARALLEL", "GP__POINT__TYPE__PARALLEL", 3 },
  { "OUTPUT", "GP__POINT__TYPE__OUTPUT", 4 },
};
static const ProtobufCIntRange gp__point__type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex gp__point__type__enum_values_by_name[5] =
{
  { "FUNCTION", 0 },
  { "INPUT", 1 },
  { "OUTPUT", 4 },
  { "PARALLEL", 3 },
  { "STRING", 2 },
};
const ProtobufCEnumDescriptor gp__point__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "GP.Point.TYPE",
  "TYPE",
  "GP__Point__TYPE",
  "GP",
  5,
  gp__point__type__enum_values_by_number,
  5,
  gp__point__type__enum_values_by_name,
  1,
  gp__point__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue gp__point__paralleltpye__enum_values_by_number[3] =
{
  { "MAP", "GP__POINT__PARALLELTPYE__MAP", 0 },
  { "REDUCE", "GP__POINT__PARALLELTPYE__REDUCE", 1 },
  { "PAL_FUNCTION", "GP__POINT__PARALLELTPYE__PAL_FUNCTION", 2 },
};
static const ProtobufCIntRange gp__point__paralleltpye__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex gp__point__paralleltpye__enum_values_by_name[3] =
{
  { "MAP", 0 },
  { "PAL_FUNCTION", 2 },
  { "REDUCE", 1 },
};
const ProtobufCEnumDescriptor gp__point__paralleltpye__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "GP.Point.PARALLELTPYE",
  "PARALLELTPYE",
  "GP__Point__PARALLELTPYE",
  "GP",
  3,
  gp__point__paralleltpye__enum_values_by_number,
  3,
  gp__point__paralleltpye__enum_values_by_name,
  1,
  gp__point__paralleltpye__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const GP__Point__TYPE gp__point__type__default_value = GP__POINT__TYPE__INPUT;
static const ProtobufCFieldDescriptor gp__point__field_descriptors[8] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GP__Point, type),
    &gp__point__type__descriptor,
    &gp__point__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "children",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GP__Point, n_children),
    offsetof(GP__Point, children),
    &gp__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input_number",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(GP__Point, has_input_number),
    offsetof(GP__Point, input_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parallel_type",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(GP__Point, has_parallel_type),
    offsetof(GP__Point, parallel_type),
    &gp__point__paralleltpye__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parallel_function",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GP__Point, parallel_function),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "function_name",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GP__Point, function_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GP__Point, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_names",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(GP__Point, n_output_names),
    offsetof(GP__Point, output_names),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gp__point__field_indices_by_name[] = {
  1,   /* field[1] = children */
  6,   /* field[6] = content */
  5,   /* field[5] = function_name */
  2,   /* field[2] = input_number */
  7,   /* field[7] = output_names */
  4,   /* field[4] = parallel_function */
  3,   /* field[3] = parallel_type */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange gp__point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor gp__point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GP.Point",
  "Point",
  "GP__Point",
  "GP",
  sizeof(GP__Point),
  8,
  gp__point__field_descriptors,
  gp__point__field_indices_by_name,
  1,  gp__point__number_ranges,
  (ProtobufCMessageInit) gp__point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
