/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/Lib.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/Lib.pb-c.h"
void   gp__lib__function__init
                     (GP__Lib__Function         *message)
{
  static GP__Lib__Function init_value = GP__LIB__FUNCTION__INIT;
  *message = init_value;
}
void   gp__lib__init
                     (GP__Lib         *message)
{
  static GP__Lib init_value = GP__LIB__INIT;
  *message = init_value;
}
size_t gp__lib__get_packed_size
                     (const GP__Lib *message)
{
  assert(message->base.descriptor == &gp__lib__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gp__lib__pack
                     (const GP__Lib *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gp__lib__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gp__lib__pack_to_buffer
                     (const GP__Lib *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gp__lib__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GP__Lib *
       gp__lib__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GP__Lib *)
     protobuf_c_message_unpack (&gp__lib__descriptor,
                                allocator, len, data);
}
void   gp__lib__free_unpacked
                     (GP__Lib *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &gp__lib__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor gp__lib__function__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GP__Lib__Function, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(GP__Lib__Function, n_output),
    offsetof(GP__Lib__Function, output),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(GP__Lib__Function, n_input),
    offsetof(GP__Lib__Function, input),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(GP__Lib__Function, n_status),
    offsetof(GP__Lib__Function, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gp__lib__function__field_indices_by_name[] = {
  2,   /* field[2] = input */
  0,   /* field[0] = name */
  1,   /* field[1] = output */
  3,   /* field[3] = status */
};
static const ProtobufCIntRange gp__lib__function__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor gp__lib__function__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GP.Lib.Function",
  "Function",
  "GP__Lib__Function",
  "GP",
  sizeof(GP__Lib__Function),
  4,
  gp__lib__function__field_descriptors,
  gp__lib__function__field_indices_by_name,
  1,  gp__lib__function__number_ranges,
  (ProtobufCMessageInit) gp__lib__function__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gp__lib__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GP__Lib, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "functions",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GP__Lib, n_functions),
    offsetof(GP__Lib, functions),
    &gp__lib__function__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gp__lib__field_indices_by_name[] = {
  1,   /* field[1] = functions */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange gp__lib__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gp__lib__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GP.Lib",
  "Lib",
  "GP__Lib",
  "GP",
  sizeof(GP__Lib),
  2,
  gp__lib__field_descriptors,
  gp__lib__field_indices_by_name,
  1,  gp__lib__number_ranges,
  (ProtobufCMessageInit) gp__lib__init,
  NULL,NULL,NULL    /* reserved[123] */
};
