/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/Lib.proto */

#ifndef PROTOBUF_C_proto_2fLib_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fLib_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _GP__Lib GP__Lib;
typedef struct _GP__Lib__Function GP__Lib__Function;


/* --- enums --- */


/* --- messages --- */

struct  _GP__Lib__Function
{
  ProtobufCMessage base;
  char *name;
  size_t n_output;
  char **output;
  size_t n_input;
  char **input;
  size_t n_status;
  char **status;
};
#define GP__LIB__FUNCTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gp__lib__function__descriptor) \
    , NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _GP__Lib
{
  ProtobufCMessage base;
  char *name;
  size_t n_functions;
  GP__Lib__Function **functions;
};
#define GP__LIB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gp__lib__descriptor) \
    , NULL, 0,NULL }


/* GP__Lib__Function methods */
void   gp__lib__function__init
                     (GP__Lib__Function         *message);
/* GP__Lib methods */
void   gp__lib__init
                     (GP__Lib         *message);
size_t gp__lib__get_packed_size
                     (const GP__Lib   *message);
size_t gp__lib__pack
                     (const GP__Lib   *message,
                      uint8_t             *out);
size_t gp__lib__pack_to_buffer
                     (const GP__Lib   *message,
                      ProtobufCBuffer     *buffer);
GP__Lib *
       gp__lib__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gp__lib__free_unpacked
                     (GP__Lib *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*GP__Lib__Function_Closure)
                 (const GP__Lib__Function *message,
                  void *closure_data);
typedef void (*GP__Lib_Closure)
                 (const GP__Lib *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor gp__lib__descriptor;
extern const ProtobufCMessageDescriptor gp__lib__function__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fLib_2eproto__INCLUDED */
